services:
  - type: web
    name: topping-express-usca
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: postmark_API_Tokens
        sync: false
      - key: STALLION_API_TOKEN
        sync: false
      - key: ADMIN_EMAIL
        value: toppingcourier.ca@gmail.com
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true
