services:
  - type: web
    name: topping-express-usca
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: STALLION_API_KEY
        sync: false
      - key: STALLION_API_URL
        value: https://api.stallionexpress.ca
      - key: POSTMARK_API_KEY
        sync: false
      - key: POSTMARK_FROM_EMAIL
        value: no-reply@toppingcourier.ca
      - key: ADMIN_EMAIL
        value: toppingcourier.ca@gmail.com
      - key: SESSION_SECRET
        generateValue: true
